package com.nam.chat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAllPropertiesEquals(Group expected, Group actual) {
        assertGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAllUpdatablePropertiesEquals(Group expected, Group actual) {
        assertGroupUpdatableFieldsEquals(expected, actual);
        assertGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupAutoGeneratedPropertiesEquals(Group expected, Group actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupUpdatableFieldsEquals(Group expected, Group actual) {
        assertThat(expected)
            .as("Verify Group relevant properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getLastMessageId()).as("check lastMessageId").isEqualTo(actual.getLastMessageId()))
            .satisfies(e -> assertThat(e.getAvatar()).as("check avatar").isEqualTo(actual.getAvatar()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupUpdatableRelationshipsEquals(Group expected, Group actual) {
        // empty method
    }
}
